# Change this value to your own domain.
base_url = "https://lmbouay.github.io/my-personal-site/"

title = ""
description = ""

# minify_html = true
compile_sass = true

[extra]
author = "ACM UMN"
menu = [
    { url = "/", name = "Home" },
]
